"""
Copyright (c) 2026 by FlashInfer team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

# JIT loader for the Cake-generated fused QK RMSNorm / NeoX RoPE / FP8
# quantize / paged KV append kernel (``backend="cake"``).
#
# The device body under ``csrc/cake/<arch>/`` is generated by the Cake compiler
# from its ``flashinfer_blackwell_fused_qk_rmsnorm_rope_fp8_paged_kv_append``
# kernel program and is compiled as its own translation unit. The host binding
# ``csrc/cake/cake_fused_qk_rope_append_binding.cu`` only depends on the
# kernel symbol, its parameter list, and the launch geometry, which this
# module resolves from the generated source itself (symbol and
# ``__launch_bounds__``) rather than from a hard-coded table.

from __future__ import annotations

import functools
import hashlib
import re
from pathlib import Path
from typing import Optional

import torch

from ...jit.core import (
    JitSpec,
    gen_jit_spec,
    logger,
    sm90a_nvcc_flags,
    sm100a_nvcc_flags,
    sm103a_nvcc_flags,
)
from ...utils import get_compute_capability
from .jit import _flashinfer_csrc_path

CAKE_KERNEL_FILE = "fused_qk_rmsnorm_rope_fp8_paged_kv_append_kernel.cu"
CAKE_BINDING_FILE = "cake_fused_qk_rope_append_binding.cu"
CAKE_DECLARATIONS_FILE = "cake_fused_qk_rope_append_declarations.cuh"
CAKE_PLACEHOLDER_MARKER = "FLASHINFER_CAKE_FUSED_QK_ROPE_APPEND_PLACEHOLDER"
CAKE_BLOCK_THREADS = 96

_ARCH_BY_CAPABILITY = {(9, 0): "sm_90a", (10, 0): "sm_100a", (10, 3): "sm_103a"}
_ARCH_FLAGS = {
    "sm_90a": sm90a_nvcc_flags,
    "sm_100a": sm100a_nvcc_flags,
    "sm_103a": sm103a_nvcc_flags,
}
_KERNEL_SIGNATURE_RE = re.compile(
    r"__global__\s+(?:__launch_bounds__\(\s*(\d+)[^)]*\)\s+)?void\s+(kernel_\w+)\s*\("
)


def cake_csrc_dir() -> Path:
    return Path(__file__).resolve().parent / "csrc" / "cake"


def cake_fused_qk_rope_append_arch(device: Optional[torch.device] = None) -> str:
    """Return the generated-source architecture directory for ``device``."""
    resolved = torch.device("cuda") if device is None else torch.device(device)
    major, minor = get_compute_capability(resolved)
    arch = _ARCH_BY_CAPABILITY.get((major, minor))
    if arch is None:
        raise RuntimeError(
            "backend='cake' for fused QK RMSNorm/RoPE/FP8 paged append requires "
            "exact compute capability 9.0 (sm_90a), 10.0 (sm_100a) or 10.3 "
            f"(sm_103a); got {major}.{minor}"
        )
    return arch


def cake_kernel_source(arch: str) -> Path:
    if arch not in _ARCH_FLAGS:
        raise ValueError(f"unsupported Cake fused QK/RoPE architecture: {arch}")
    return cake_csrc_dir() / arch / CAKE_KERNEL_FILE


def is_cake_fused_qk_rope_append_available(
    device: Optional[torch.device] = None,
) -> bool:
    """Return whether a real (non-placeholder) generated body exists for ``device``."""
    try:
        source = cake_kernel_source(cake_fused_qk_rope_append_arch(device))
        return source.is_file() and CAKE_PLACEHOLDER_MARKER not in source.read_text()
    except (FileNotFoundError, RuntimeError, ValueError, OSError):
        return False


def _resolve_kernel_signature(source: Path, text: str) -> tuple[str, int]:
    matches = _KERNEL_SIGNATURE_RE.findall(text)
    if len(matches) != 1:
        raise RuntimeError(
            f"expected exactly one generated __global__ kernel in {source}, "
            f"found {len(matches)}"
        )
    threads, symbol = matches[0]
    if not threads:
        raise RuntimeError(
            f"generated kernel {symbol} in {source} has no __launch_bounds__; "
            "cannot resolve the block size"
        )
    return symbol, int(threads)


@functools.cache
def gen_cake_fused_qk_rope_append_module(arch: str) -> JitSpec:
    """Create the JIT specification for one generated architecture."""
    source = cake_kernel_source(arch)
    if not source.is_file():
        raise FileNotFoundError(
            f"generated Cake fused QK/RoPE FP8 source not found: {source}"
        )
    text = source.read_text()
    if CAKE_PLACEHOLDER_MARKER in text:
        raise RuntimeError(
            f"the Cake fused QK/RoPE FP8 source for {arch} is a placeholder; "
            "install the generated kernel before selecting backend='cake'"
        )
    csrc_dir = cake_csrc_dir()
    binding = csrc_dir / CAKE_BINDING_FILE
    declarations = csrc_dir / CAKE_DECLARATIONS_FILE
    for required in (binding, declarations):
        if not required.is_file():
            raise FileNotFoundError(
                f"Cake fused QK/RoPE host source not found: {required}"
            )
    symbol, threads = _resolve_kernel_signature(source, text)
    if threads != CAKE_BLOCK_THREADS:
        raise RuntimeError(
            f"generated kernel {symbol} declares __launch_bounds__({threads}); the "
            f"binding launches {CAKE_BLOCK_THREADS} threads per CTA"
        )
    digest = hashlib.sha256(source.read_bytes()).hexdigest()[:16]
    major, minor = next(cc for cc, name in _ARCH_BY_CAPABILITY.items() if name == arch)
    spec = gen_jit_spec(
        name=f"cake_fused_qk_rope_append_{arch}_{digest}",
        sources=[source, binding],
        extra_cuda_cflags=[
            *_ARCH_FLAGS[arch],
            f"-DCAKE_FUSED_QK_ROPE_APPEND_KERNEL={symbol}",
            f"-DCAKE_FUSED_QK_ROPE_APPEND_THREADS={threads}",
            f"-DCAKE_FUSED_QK_ROPE_APPEND_CC_MAJOR={major}",
            f"-DCAKE_FUSED_QK_ROPE_APPEND_CC_MINOR={minor}",
        ],
        extra_include_paths=[csrc_dir, _flashinfer_csrc_path()],
        # The Cake compiler emits the body for plain NVRTC (no fast-math); keep
        # the numerics of the generated kernel unchanged.
        use_fast_math=False,
    )
    logger.info("Generated Cake fused QK/RoPE FP8 %s JIT spec: %s", arch, spec.name)
    return spec


@functools.cache
def _load(arch: str):
    module = gen_cake_fused_qk_rope_append_module(arch).build_and_load()
    logger.info("Loaded Cake fused QK/RoPE FP8 %s module", arch)
    return module


def load_cake_fused_qk_rope_append_module(device: Optional[torch.device] = None):
    """Build or load the generated module matching ``device``'s architecture."""
    return _load(cake_fused_qk_rope_append_arch(device))


__all__ = [
    "CAKE_BLOCK_THREADS",
    "CAKE_PLACEHOLDER_MARKER",
    "cake_fused_qk_rope_append_arch",
    "cake_kernel_source",
    "gen_cake_fused_qk_rope_append_module",
    "is_cake_fused_qk_rope_append_available",
    "load_cake_fused_qk_rope_append_module",
]
